export const userData = [
  {
    patientName: "mahesh",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh001",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith001",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya001",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh002",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith002",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya002",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh003",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith003",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya003",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh004",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith004",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya004",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh005",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith005",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya005",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh006",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith006",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya006",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh007",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith007",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya007",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh008",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith008",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya008",
    gender: "female",
    age: "32",
    patientId: "834",
  },
  {
    patientName: "mahesh009",
    gender: "Male",
    age: "22",
    patientId: "829",
  },
  {
    patientName: "ranjith009",
    gender: "Male",
    age: "25",
    patientId: "832",
  },
  {
    patientName: "ramya009",
    gender: "female",
    age: "32",
    patientId: "834",
  },
];
